FROM medbelouaer/msbuild:latest as builder
SHELL ["powershell"]

COPY . 'C:\\build\\'
WORKDIR 'C:\\build\\'

RUN ["nuget", "restore"]
RUN ["msbuild", "C:\\build\\WebApplication1.sln"]
CMD ["powershell"]

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
WORKDIR /inetpub/wwwroot
COPY --from=builder "C:\\build\\WebApplication1\\" .
